DEX-972 Order routes tests
wavesplatform/matcher pull request #419
Opened 2020-12-07 10:56 UTC by ngadiyak

2020-12-07 14:00 UTC, vsuharnikov requested changes

2020-12-07 17:17 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/cancel/CancelAllOrdersSpec.scala
> +      })
fixed

2020-12-07 17:17 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/place/package.scala
> +  val orderCases = Table(
good idea, fixed

2020-12-07 17:17 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/place/PlaceLimitOrderSpec.scala
> +        validateMatcherErrorContainText(dex1.rawApi.place(mkOrder(alice, wavesUsdPair, BUY, a, p, f, fa, t, d, v, pk)), c, e, m)
ok!

2020-12-07 17:17 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/place/PlaceMarketOrderSpec.scala
> +    forAll(orderCases) { (n: Int, a: Long, p: Long, f: Long, fa: Asset, t: Long, d: Duration, v: Byte, pk: account.PublicKey, c: Int, e: Int, m: String) =>
fixed

2020-12-07 17:23 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/cancel/CancelOrderSpec.scala
> +    //TODO: maybe there is should be 404 ?
ok

2020-12-07 17:23 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/cancel/CancelOrdersByAddressAndIdsSpec.scala
> +      })
ok

2020-12-07 17:23 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/cancel/CancelOrderByIdSpec.scala
> +    //TODO: maybe there is should be 404?
ok

2020-12-07 17:23 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/cancel/CancelOrderByIdSpec.scala
> +    //TODO: maybe there is should be 404?
1024

2020-12-07 17:23 UTC, ngadiyak commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/cancel/CancelOrdersByAddressAndIdsSpec.scala
> +      val r = validate200Json(dex1.rawApi.cancelAllByAddressAndIds(toAddress(alice).stringRepr, ids))
done

2020-12-08 06:49 UTC, vsuharnikov commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/place/PlaceOrderBaseSpec.scala
> +class PlaceOrderBaseSpec extends MatcherSuiteBase with TableDrivenPropertyChecks with RawHttpChecks {
👍

2020-12-08 06:50 UTC, vsuharnikov approved these changes

2020-12-08 06:50 UTC, merged