DEX-1155 fix sync with node
wavesplatform/matcher pull request #526
Opened 2021-04-22 13:25 UTC by alexander-branevskiy

2021-04-22 13:52 UTC, JennaWestenra approved these changes

2021-04-23 09:01 UTC, vsuharnikov requested changes
I've found, that we can't forcefully restart the synchronization.
This happens because a channel in `GrpcBlockchainUpdatesControlledStream.BlockchainUpdatesObserver.scheduleRestart` isn't stopped in `stopGrpcObserver` even we call `cancel`, see the last lines in `Issue` before `Solution` in the task for more details. 
So `onError` isn't called and `internalSystemStream` don't receive `SystemEvent.Stopped`. This causes `CombinedStream` to do nothing.

Let's close the channel in `GrpcBlockchainUpdatesControlledStream.stopGrpcObserver and stop`. Also you could try to share this code between `stop` and `stopGrpcObserver`.

2021-04-24 09:48 UTC, vsuharnikov commented on dex-it/src/test/scala/com/wavesplatform/it/sync/orders/OrderDynamicFeeTestSuite.scala
> +      dex1.restartWithNewSuiteConfig(ConfigFactory.parseString("waves.dex.order-fee.-1.mode = percent").withFallback(dexInitialSuiteConfig))
👍

2021-04-24 15:20 UTC, vsuharnikov approved these changes

2021-04-24 15:21 UTC, merged