DEX-1161 log docker ports
wavesplatform/matcher pull request #555
Opened 2021-05-21 14:48 UTC by JennaWestenra

Logging format:

```
13:08:34.872 INFO  [1-thread-1] c.w.d.i.d.DexContainer - Started container; Exposed ports for networks [waves-1865344633]: 6886 -> 55018/tcp; 10001 -> 55017/tcp
.....
Connected container to network; Exposed ports for networks [waves-1865344633]: 6871 -> 55021/tcp; 6887 -> 55019/tcp; 6870 -> 55022/tcp; 6869 -> 55023/tcp; 6868 -> 55024/tcp; 6881 -> 55020/tcp; 6863 -> 55025/tcp; 6862 -> 55026/tcp
```

2021-05-22 18:59 UTC, alexander-branevskiy requested changes

2021-05-22 18:59 UTC, alexander-branevskiy commented on dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala
> +  private def logExposedPortsInfo(prefix: String): Unit = {
let's do minor refactors!)

```
  private def logExposedPortsInfo(prefix: String): Unit = {
    val networkSettings = dockerClient
      .inspectContainerCmd(underlying.containerId)
      .exec()
      .getNetworkSettings
    val portBindingsStr = networkSettings
      .getPorts
      .getBindings
      .asScala
      .flatMap { case (exposedPort, portBindings) =>
        portBindings.headOption.map { containerPort =>
          s"${exposedPort.getPort} -> ${containerPort.getHostPortSpec}/${exposedPort.getProtocol}"
        }
      }
      .mkString("; ")
    log.info(s"$prefix Exposed ports for networks ${networkSettings.getNetworks.keySet()}: $portBindingsStr")
  }
```

2021-05-24 09:02 UTC, vsuharnikov approved these changes

2021-05-24 09:04 UTC, alexander-branevskiy approved these changes

2021-05-24 10:16 UTC, merged