DEX-1216 Remove ForceStartOrderBook
wavesplatform/matcher pull request #599
Opened 2021-06-17 09:31 UTC by JennaWestenra

2021-06-17 11:40 UTC, vsuharnikov requested changes

2021-06-17 11:40 UTC, vsuharnikov commented on dex/src/main/scala/com/wavesplatform/dex/actors/OrderBookDirectoryActor.scala
> +  case class OrderBookIsAvailable(assetPair: AssetPair)
It seems we don't use this.

2021-06-17 11:40 UTC, vsuharnikov commented on dex/src/main/scala/com/wavesplatform/dex/actors/OrderBookDirectoryActor.scala
> +  case class AggregatedOrderBookEnvelopeSent(assetPair: AssetPair)
This class is used only in tests. It seems we don't need this class too.

2021-06-18 11:41 UTC, vsuharnikov approved these changes

2021-06-18 12:05 UTC, vsuharnikov commented on dex-it/src/test/scala/com/wavesplatform/it/matcher/api/http/debug/GetOldestSnapshotOffsetSpec.scala
> +      validate200Json(dex1.rawApi.getOldestSnapshotOffset) should be(0)
Probably we need to wrap this to `eventually`, because a snapshot might not be created in this time

2021-06-21 07:56 UTC, vsuharnikov approved these changes

2021-06-21 09:09 UTC, alexander-branevskiy approved these changes

2021-06-21 09:51 UTC, merged