DEX-1332 Extend order WS information
wavesplatform/matcher pull request #615
Opened 2021-08-12 06:25 UTC by JennaWestenra

2021-08-12 08:27 UTC, ngadiyak approved these changes

2021-08-12 09:09 UTC, vsuharnikov requested changes

2021-08-12 09:09 UTC, vsuharnikov commented on dex/src/main/scala/com/wavesplatform/dex/api/ws/entities/WsMatchTransactionInfo.scala
> +    def calcAmountOfPriceAssets(): Long = BigDecimal.valueOf(executedAmountAssets)
Let's create a function`amountOfPriceAsset` in `AcceptedOrder` companion object and use it in `accepterOrder. amountOfPriceAsset` and here

2021-08-13 14:25 UTC, alexander-branevskiy requested changes

2021-08-13 14:25 UTC, alexander-branevskiy commented on waves-integration/src/main/scala/com/wavesplatform/dex/domain/transaction/ExchangeTransactionResult.scala
> +  def toOptionTx: Option[A] = error.fold(transaction.some)(_ => None)
toOption

2021-08-13 14:25 UTC, alexander-branevskiy commented on waves-integration/src/main/scala/com/wavesplatform/dex/domain/transaction/ExchangeTransactionResult.scala
> +  def transformTx[B <: ExchangeTransaction](f: A => B): ExchangeTransactionResult[B] =
map

2021-08-16 08:16 UTC, vsuharnikov requested changes

2021-08-16 08:16 UTC, vsuharnikov commented on dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WsMessageOps.scala
> +            }.map(c => id -> c.copy(matchInfo = c.matchInfo.distinct))
We can't receive one tx twice. Please, remove `distinct`, it could catch a bug.

2021-08-16 08:29 UTC, vsuharnikov approved these changes

2021-08-16 08:36 UTC, alexander-branevskiy approved these changes

2021-08-16 09:14 UTC, merged