DEX-1497 extend ws order info
wavesplatform/matcher pull request #663
Opened 2021-11-22 04:23 UTC by JennaWestenra

2021-11-22 13:01 UTC, alexander-branevskiy requested changes

2021-11-22 13:07 UTC, ngadiyak approved these changes

2021-11-22 13:12 UTC, alexander-branevskiy commented on dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
> +    amountAsset = orig.amountAsset,
probably we should add some assert her verifying that orig & diff ```amountAsset, priceAsset, side``` are equal

2021-11-23 07:39 UTC, alexander-branevskiy approved these changes

2021-11-23 08:19 UTC, alxndrmkd approved these changes

2021-11-23 08:19 UTC, merged