DEX-1428 send match ws updates in batch
wavesplatform/matcher pull request #671
Opened 2021-12-10 05:30 UTC by JennaWestenra

2021-12-16 07:00 UTC, alxndrmkd approved these changes

2021-12-17 08:42 UTC, ngadiyak approved these changes

2021-12-17 12:55 UTC, alexander-branevskiy requested changes

2021-12-17 12:55 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActor.scala
> +  private def processEvents(timestamp: Long, events: IterableOnce[Event]): Unit = {
```
  private def processEvents(timestamp: Long, events: List[Event]): Unit = {
    val changes = events.flatMap { event =>
      logEvent(event)
      // DEX-1192 docs/places-and-cancels.md
      event match {
        case event: Events.OrderExecuted => WsOrdersUpdate.from(event, timestamp).some
        case event: Events.OrderCanceled => WsOrdersUpdate.from(event).some
        case _ => none
      }
    }
    NonEmptyList.fromList(events).foreach(eventsCoordinatorRef ! OrderEventsCoordinatorActor.Command.Process(_))

    changes.map(WsInternalBroadcastActor.Command.Collect).foreach(wsInternalHandlerDirectoryRef ! _)
  }
  ````

2021-12-17 12:55 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActor.scala
> +  private def processEvents(timestamp: Long, events: IterableOnce[Event]): Unit = {
rewrite to this. and convert .toList for each invocation. should look better

2021-12-17 12:55 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
> +          val (updated, changes: AddressBalance.Changes) =
explicit type here can be omitted

2021-12-17 12:55 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
> +      def events: Iterable[Events.Event]
why we change this?

2021-12-17 12:58 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/actors/events/OrderEventsCoordinatorActor.scala
> +          NonEmptyList.fromList(orderExecutedEvents).map(nel => AddressActor.Command.ApplyOrderBookExecuted(nel)).foreach(addressDirectoryRef ! _)
```.map(AddressActor.Command.ApplyOrderBookExecuted(_))``` or probably even ```.map(AddressActor.Command.ApplyOrderBookExecuted)```

2021-12-17 13:04 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/HasOecInteraction.scala
> +    def expectOecProcess[T <: Events.Event](implicit ct: ClassTag[T]): NonEmptyList[T] =
```
    def expectOecProcess[T <: Events.Event](implicit ct: ClassTag[T]): NonEmptyList[T] =
      NonEmptyList.fromListUnsafe(self.expectMsgType[Process].events.toList).map {
        case x: T => x
        case ev => fail(s"Expected ${ct.runtimeClass.getName}, given: $ev")
      }
      ```

2021-12-17 13:05 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/HasOecInteraction.scala
> +    def expectOecProcess[T <: Events.Event](implicit ct: ClassTag[T]): NonEmptyList[T] =
btw what is oec ?

2021-12-17 13:05 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/HasOecInteraction.scala
> +        case (head: T) :: _ => head
pattern match case Nil will fail

2021-12-17 13:09 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/HasOecInteraction.scala
> +    def expectOecProcess[T <: Events.Event](implicit ct: ClassTag[T]): NonEmptyList[T] =
your variant will fail on ```case Nil```

2021-12-17 13:13 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
> +          val currentUpdate = WsOrderExecutedUpdates(ownerRemainingOrders.map(k => AcceptedOrderWithTx(k, txResult)), changes)
AcceptedOrderWithTx(_, txResult)

2021-12-17 13:18 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressBalance.scala
> +          x.removedNotCreatedTxs ++ y.removedNotCreatedTxs
:+1:

2021-12-17 13:20 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/HasOecInteraction.scala
> +    private def loop[T <: Events.Event](events: List[Events.Event])(implicit ct: ClassTag[T]): NonEmptyList[T] =
will fail on pattern match case Nil

2021-12-17 21:03 UTC, alexander-branevskiy approved these changes

2021-12-20 06:34 UTC, merged

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +      val events = tp.expectMsgType[Process].events
```
val events = tp.expectMsgType[Process].events.toList
```

and then 
```
events.size shouldBe 2
events.head
events.last
```

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +      events.collect { case a: OrderExecuted => a }.size should be >= 1
can we do an exact match?

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +      events.collect { case a: OrderExecuted => a }.size should be >= 1
and also check expected Process size

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +      tp.expectOecProcess[OrderAdded].head should matchTo(
expectFirstOec

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +      tp.expectOecProcess[OrderAdded].head should matchTo(
expectFirstOec

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +      tp.expectOecProcess[OrderAdded].head should matchTo(
expectFirstOec

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +        val events = tp.expectMsgType[Process].events
pls check Process expected size

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +        val events = tp.expectMsgType[Process].events
pls check Process expected size

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +          val events = tp.expectMsgType[Process].events
pls check Process expected size

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +          val events = tp.expectMsgType[Process].events
pls check Process expected size

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +          val events = tp.expectMsgType[Process].events
pls check Process expected size

2021-12-21 14:57 UTC, alexander-branevskiy commented on dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
> +      tp.expectOecProcess[OrderCanceled].head.reason shouldBe Events.OrderCanceledReason.OrderBookDeleted
expectFirstOec