DEX-1707 leveldb metrics
wavesplatform/matcher pull request #756
Opened 2022-10-04 14:07 UTC by JennaWestenra

2022-10-04 14:12 UTC, stavegan approved these changes

2022-10-04 14:14 UTC, stavegan commented on dex/src/main/scala/com/wavesplatform/dex/db/OrderDb.scala
> +    override def status(id: Order.Id): Future[OrderStatus.Final] = measureDb(cls, "status") { () =>
break line

2022-10-05 14:06 UTC, alexander-branevskiy requested changes

2022-10-05 14:06 UTC, alexander-branevskiy commented on dex/src/main/scala/com/wavesplatform/dex/db/AssetPairsDb.scala
> +  private val cls = "AssetPairsDb"
```getClass.getSimpleName.filter(_ != '$')```

and for all places like this

2022-10-06 12:50 UTC, alexander-branevskiy approved these changes

2022-10-06 13:43 UTC, merged